# Generated by Django 6.0.1 on 2026-08-30 07:18

from django.db import migrations, models

def safe_alter_reason(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_schema = 'public' 
                          AND table_name = 'bookings_appointment' 
                          AND column_name = 'reason'
                    ) THEN
                        ALTER TABLE bookings_appointment ALTER COLUMN reason DROP NOT NULL;
                        ALTER TABLE bookings_appointment ALTER COLUMN reason SET DEFAULT '';
                    END IF;
                END $$;
            """)

class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='appointment',
                    name='reason',
                    field=models.TextField(blank=True, default=''),
                ),
            ],
            database_operations=[
                migrations.RunPython(safe_alter_reason, reverse_code=migrations.RunPython.noop),
            ]
        ),
    ]
