# Generated by Django 6.0.1 on 2026-03-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('WASH', 'Water, Sanitation and Hygiene (WASH)'), ('PEACE_BUILDING', 'Peace Building & Conflict Resolution'), ('SUSTAINABLE_AGRIC', 'Sustainable Agriculture'), ('EMPOWERMENT', 'Women and Youth Empowerment'), ('PRISON_APOSTOLATE', 'Prison Apostolate & Legal Aid'), ('GENERAL', 'General Impact')], default='GENERAL', max_length=100),
        ),
    ]
