# Generated by Django 6.0.1 on 2026-02-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Annual Report', 'Annual Report'), ('Newsletter', 'Newsletter'), ('Legal Aid', 'Legal Aid'), ('Other', 'Other')], max_length=50)),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='resources/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='resources/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
