# Generated by Django 6.0.1 on 2026-08-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('ANNUAL_REPORT', 'Annual Report'), ('NEWSLETTER', 'Newsletter'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
