# Generated by Django 6.0.1 on 2026-08-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('ANNUAL_REPORT', 'Annual Report'), ('NEWSLETTER', 'Newsletter'), ('OTHER', 'Other')], default='ANNUAL_REPORT', max_length=50),
        ),
    ]
