# Generated by Django 6.0.1 on 2026-01-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(default='bg-green-500', max_length=50)),
                ('description', models.TextField()),
                ('full_content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/')),
            ],
        ),
    ]
